### ISSUE TITLE
win10运行报错

### ISSUE THREAD

**Issue by don59** [rememberber/WePush#13]
![_20170706091933](https://user-images.githubusercontent.com/8613083/27891475-b67ba7b8-622c-11e7-9504-d2a31405b93c.png)

**Comment by rememberber** [comment]
安装到哪个磁盘了？java版本是什么？

**Comment by don59** [comment]
c盘,1.8.0

> java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

**Comment by rememberber** [comment]
目前阶段还不能安装到C盘
