### ISSUE TITLE
请教一下，通过文件导入的openid/手机号文件格式是怎样的？谢谢！

### ISSUE THREAD

**Issue by GeminiAspros** [rememberber/WePush#14]
想导入自己的手机号测试学习一下，谢谢！

**Comment by rememberber** [comment]
@GeminiAspros 先确认一下自己是否有公众号可以配置，是否有阿里大于的模板短信可以配置，这些都在设置里配置好之后就可以试了，只给自己试发的时候可以使用编辑消息中的预览功能
