### ISSUE TITLE
在发送客服消息的文本消息时候失败errcode:44004

### ISSUE THREAD

**Issue by chijincn** [rememberber/WePush#211]
### 现象描述

在发送客服消息的文本消息时候失败

### 环境信息

Windows7 64位

### 重现步骤

[在此填写能够重现该问题的操作步骤]

- 步骤1，选择消息类型->公众号-客服消息
- 步骤2，编辑消息->新建->消息类型文本消息
- 步骤3，输入内容：一条客服文本消息，<a href="https://www.baidu.com">去百度</a>
- 步骤5，使用个人微信号向公众号发送一条消息，确保已经互动
- 步骤6，开始推送，去除勾选的空跑，点击 开始按钮
- 步骤7，显示全部失败

### 报错信息

10:24:47.455 [main] INFO  c.f.tool.push.util.UpgradeUtil :100 - 平滑升级开始
10:24:51.905 [main] INFO  c.f.tool.push.util.UpgradeUtil :117 - 旧版本v_3.6.2_190811
10:24:51.940 [main] INFO  c.f.tool.push.util.UpgradeUtil :118 - 当前版本v_3.6.3_190825
10:24:51.990 [main] INFO  c.f.tool.push.util.UpgradeUtil :122 - 更新版本索引32开始
10:24:52.050 [main] INFO  c.f.tool.push.util.UpgradeUtil :155 - 执行升级脚本开始，版本索引：32
10:24:52.115 [main] INFO  c.f.tool.push.util.UpgradeUtil :220 - 执行升级脚本结束，版本索引：32
10:24:52.166 [main] INFO  c.f.tool.push.util.UpgradeUtil :139 - 更新版本索引32结束
10:24:52.238 [main] INFO  c.f.tool.push.util.UpgradeUtil :145 - 平滑升级结束
10:25:41.631 [pool-3-thread-2] WARN  c.f.tool.push.util.ConsoleUtil :30 - 关注该公众账号的总用户数：14
10:25:41.633 [pool-3-thread-2] WARN  c.f.tool.push.util.ConsoleUtil :30 - 拉取的OPENID个数：14
10:25:41.729 [pool-3-thread-2] WARN  c.f.tool.push.util.ConsoleUtil :30 - 拉取的OPENID个数：0
10:25:51.170 [pool-3-thread-2] WARN  c.f.tool.push.util.ConsoleUtil :30 - 拉取的OPENID个数：2
10:25:51.234 [pool-3-thread-2] WARN  c.f.tool.push.util.ConsoleUtil :30 - 拉取的OPENID个数：0
10:26:10.315 [pool-3-thread-4] WARN  c.f.tool.push.util.ConsoleUtil :30 - 消息总数：2
10:26:10.316 [pool-3-thread-4] WARN  c.f.tool.push.util.ConsoleUtil :30 - 可用处理器核心：4
10:26:10.349 [pool-3-thread-4] WARN  c.f.tool.push.util.ConsoleUtil :30 - 线程数：23
10:26:10.408 [pool-3-thread-4] WARN  c.f.tool.push.util.ConsoleUtil :30 - 线程池大小：100
10:26:10.419 [pool-3-thread-4] WARN  c.f.tool.push.util.ConsoleUtil :30 - 推送开始……
10:26:10.428 [pool-4-thread-1] WARN  c.f.tool.push.util.ConsoleUtil :30 - 线程T-0负责处理第:0-1条数据
10:26:10.429 [pool-4-thread-2] WARN  c.f.tool.push.util.ConsoleUtil :30 - 线程T-1负责处理第:1-2条数据
10:26:10.430 [pool-3-thread-4] WARN  c.f.tool.push.util.ConsoleUtil :30 - 所有线程宝宝启动完毕……
10:26:10.727 [pool-4-thread-1] ERROR m.c.w.m.api.impl.BaseWxMpServiceImpl :344 - 
【请求地址】: https://api.weixin.qq.com/cgi-bin/message/custom/send?access_token=25_cNbFvO_PZhHkHLuZTM8x1bJOkstKYrGK9MbwwEee0EX3zmlkNs5nxMYeBqJEH2b-4qrWEzfdVUeIVrlaPpajf80UrgsF_MleJsh8kIXGRaoLCdYBvsh7u55ACJKa_GZzjAu8HWrxLio2TGdaXJBiADAPBT
【请求参数】：{"touser":"okmq0twCiVuRiF4_8C2i_lw9n8gg","msgtype":"text","text":{"content":""}}
【错误信息】：**{"errcode":44004,"errmsg":"empty content hint: [QIjKVA0170shb1]"}
10:26:10.728 [pool-4-thread-1] ERROR c.f.t.p.l.msgsender.WxKefuMsgSender :44 - me.chanjar.weixin.common.error.WxErrorException: {"errcode":44004,"errmsg":"empty content hint: [QIjKVA0170shb1]"}**
10:26:10.742 [pool-4-thread-1] WARN  c.f.tool.push.util.ConsoleUtil :30 - T-0已处理完第0-1条的数据
10:26:10.831 [pool-4-thread-2] ERROR m.c.w.m.api.impl.BaseWxMpServiceImpl :344 - 
【请求地址】: https://api.weixin.qq.com/cgi-bin/message/custom/send?access_token=25_1W_T7MgefgjGjlMpTM8x1bJOkstKYrGK9MbwwEee0EX3zmlkNs5nxMYeBqLSqMdBY_pqUiGH8M5e1y943bZCZFAXnghNLM0JQVAjXi3MDyxRKV9MtvVu3YxP5aJGZ4KOd0F3zq-mOT1VUMbMYOEiADAGWM
【请求参数】：{"touser":"okmq0t36FiLuqoVIdM0lujnfh4W4","msgtype":"text","text":{"content":""}}
【错误信息】：{"errcode":45015,"errmsg":"response out of time limit or subscription is canceled hint: [_KkmOA01703055]"}
10:26:10.832 [pool-4-thread-2] ERROR c.f.t.p.l.msgsender.WxKefuMsgSender :44 - me.chanjar.weixin.common.error.WxErrorException: {"errcode":45015,"errmsg":"response out of time limit or subscription is canceled hint: [_KkmOA01703055]"}
10:26:10.833 [pool-4-thread-2] WARN  c.f.tool.push.util.ConsoleUtil :30 - T-1已处理完第1-2条的数据
10:26:12.167 [pool-3-thread-4] WARN  c.f.tool.push.util.ConsoleUtil :30 - 正在保存结果数据……
10:26:13.545 [pool-3-thread-4] WARN  c.f.tool.push.util.ConsoleUtil :30 - 结果数据保存完毕！

**Comment by rememberber** [comment]
感谢反馈，经调查，是bug，已经修复，会在下一版更新，如果等不及更新，可以clone本项目在项目中运行WePush
