### ISSUE TITLE
希望支持私有化部署的企业微信

### ISSUE THREAD

**Issue by chaos-cn** [rememberber/WePush#272]
在本项目使用的weixin-java-cp-4.1.0.jar  -> me.chanjar.weixin.cp.config.impl.WxCpDefaultConfigImpl.class:50
中存在如下代码：
`
        if (this.baseApiUrl == null) {
            this.baseApiUrl = "https://qyapi.weixin.qq.com";
        }
`
默认是直接调用腾讯官方的企业微信服务器，但是企业微信支持私有化部署，当私有化部署时此域名会发生变化

我在本项目的 [com.fangxuele.tool.push.logic.msgsender.WxCpMsgSender](https://github.com/rememberber/WePush/blob/master/src/main/java/com/fangxuele/tool/push/logic/msgsender/WxCpMsgSender.java) 第89行
增加configStorage.setBaseApiUrl("https://myserver.host.com/");
测试后验证通过，推送功能正常

希望作者能将此功能加入设置的配置项中，兼容官方企业微信和私有化部署版企业微信的推送功能。

**Comment by wq57wq57** [comment]
牛

**Comment by rememberber** [comment]
好的

**Comment by rememberber** [comment]
已支持，请下载最新版

**Comment by chaos-cn** [comment]
@rememberber 初步测试了一下，功能正常，但是UI样式上存在若干问题
# 本机环境
WePush_5.0.2
M1 Mac 13.5.2
openjdk version "17.0.7" 2023-04-18 LTS

# 问题一 初始打开时 “私有BaseApiUrl” 可见性有问题
https://github.com/rememberber/WePush/assets/71205599/d554d438-2d4f-41aa-a6b5-2d43da340408

# 问题二 图文消息编辑框不一致
https://github.com/rememberber/WePush/assets/71205599/ff3b9580-684a-4dcc-9485-2d95d2f83730

**Comment by rememberber** [comment]
感谢反馈，我处理下

**Comment by rememberber** [comment]
> @rememberber 初步测试了一下，功能正常，但是UI样式上存在若干问题
> 
> # 本机环境
> WePush_5.0.2 M1 Mac 13.5.2 openjdk version "17.0.7" 2023-04-18 LTS
> 
> # 问题一 初始打开时 “私有BaseApiUrl” 可见性有问题
>  default.mp4 
> # 问题二 图文消息编辑框不一致
>  default.mp4

@chaos-cn 已解决，更新最新版试试
