### ISSUE TITLE
什么时候发布个MAC版本啊？

### ISSUE THREAD

**Issue by freefish1218** [rememberber/WePush#28]

**Comment by rememberber** [comment]
有过这个打算，没有这mac上的打包经验，我尽量。。
也希望有这方面经验的朋友帮忙打包移植

**Comment by freefish1218** [comment]
@rememberber  谢谢回复！试了下，在mac上直接双击jar包： fangxuele-tool-wechat-push-1.0.jar 就可以运行了。已经看到新版本更新，辛苦啦！

**Comment by rememberber** [comment]
@freefish1218 嗯嗯，我可以根据你的思路为Mac用户临时弄个压缩包，
后续再继续做更优雅的安装和启动方式；

目前在Mac上运行发现了字体字号异常，Dock图标异常，这两个问题已经解决，下一版本更新就有了
也欢迎你把在Mac中使用时的其他问题反馈给我，感谢~

「导入全员（自动导入当前所有关注公众号的用户）」功能中增加一个按标签筛选的功能，
这个问题，我明天看一下，如果可行，下一版也一并加上

**Comment by freefish1218** [comment]
@rememberber  太棒啦！我会持续关注的，有问题第一时间反馈过来，这个项目非常赞！加油加油！
