### ISSUE TITLE
关于swing组件初始化的一点疑惑

### ISSUE THREAD

**Issue by 2FA0** [rememberber/WePush#44]
作者你好，我在看MainWindow.java这个启动类的时候感觉很疑惑，所有的布局都没有用java语言写（代码里没看到），所有的private变量都是只有声明没有初始化，而且在main类当中我看到除了主界面那个“关于”页面以及字体的初始化之外其他的都是直接绑定的listener（找不到初始化），调试也没有看到这些swing组件都是怎么初始化的，除了一个可疑的form后缀文件之外丝毫找不到任何跟布局有关的东西（但是我删除了form文件重新编译还是没有问题依然可以运行）。
所以我觉的很奇怪，可以透露下项目里的界面组件是什么时候或者怎么new出来的吗？
![20180301161939](https://user-images.githubusercontent.com/11802492/36834754-d535e21a-1d6e-11e8-8093-d16c61a6e3f4.png)
![20180301162237](https://user-images.githubusercontent.com/11802492/36834755-d5b33026-1d6e-11e8-903b-36af75059c66.png)

**Comment by rememberber** [comment]
感谢关注，
你发的图片我这边显示挂掉了，
根据你的描述回答：
你用的是intellij idea吗?
如果是的话，form文件就是使用intellij创建的GUI form文件，
intellij 的GUI form将组件的初始化（布局、样式等）和代码分离，
你通过在src下右键也可以创建一个GUI form，
默认intellij可以自动根据form的内容编译出java源码。
如果你想看它究竟初始化了些什么内容（具体代码），
可以将IntelliJ设置一下：  
![IntelliJ GUI Designer设置](https://github.com/rememberber/WePush/blob/master/screen_shoot/%E5%9B%BE%E5%83%8F%20218.png?raw=true)
