### ISSUE TITLE
package打包jar，无法启动问题

### ISSUE THREAD

**Issue by zhengweis** [rememberber/WePush#47]
mvn package打包成功，
![image](https://user-images.githubusercontent.com/7866688/38122633-b9616cf2-3408-11e8-9f62-c3b1893b2708.png)
![image](https://user-images.githubusercontent.com/7866688/38122642-c51eac80-3408-11e8-8eaf-ef2a167e5974.png)
放到dist，启动没反应，什么情况？

**Comment by rememberber** [comment]
打包之前先调整一下intellij GUI设置
详见:https://github.com/rememberber/WePush/wiki/build

**Comment by zhengweis** [comment]
@rememberber  没问题了，是两个jar导致，在lib下面有了 我直接add as lib，但打包时本地仓库没有，所以跑不起来，建议用一个来源 以免产生误导。
<dependency>
            <groupId>com.darcula</groupId>
            <artifactId>darcula-lnf</artifactId>
            <version>1.0</version>
        </dependency>

        <dependency>
            <groupId>com.beautyeye</groupId>
            <artifactId>beautyeye-lnf</artifactId>
            <version>1.0</version>
        </dependency>
