### ISSUE TITLE
请问，还准备支持腾讯云短信跟小程序消息嘛

### ISSUE THREAD

**Issue by howe** [rememberber/WePush#50]
请问，还准备支持腾讯云短信跟小程序消息嘛

**Comment by rememberber** [comment]
@howe 小程序消息会支持，腾讯云短信也会考虑

**Comment by rememberber** [comment]
@howe 已支持小程序模板消息和腾讯云短信，欢迎下载最新版，由于环境有限，测试的不够详细，有问题及时反馈

**Comment by howe** [comment]
@rememberber 感谢，我先用起来
