### ISSUE TITLE
微信小程序模板信息中FORMID问题

### ISSUE THREAD

**Issue by backnero** [rememberber/WePush#55]
下发微信小程序的模板信息；除了提供用户的openid外，还需要提供用户的FORMID，并且每个formid是只能使用一次；在wepush中有填写formid的地方，单独给用户发没有问题，但大量群发的时候，请问在wepush中如何填写formid？谢谢

**Comment by rememberber** [comment]
现在确实存在这个问题，下一版本修复，感谢支持！

**Comment by rememberber** [comment]
最新版已经解决这个问题了，请各位试试看，准备用户的时候，第一列openid,第二列formid，如果是csv或者txt导入，两列之间半角逗号隔开

**Comment by lioilgb** [comment]
可以了。好用！

**Comment by qdstar** [comment]
新版没有fromid 是不是不能给小程序发送模板消息了 提示错 总用户数：1
总页数：1
每个线程分配：3页
需要：1个线程宝宝齐力合作
所有线程宝宝启动完毕……
线程T-0负责处理:0-2页的数据
发送失败:1;openid:oRXbnt-oxduk****x5cSaFQP8Tfs
T-0已处理完第0-2页的数据
正在保存结果数据……
结果数据保存完毕！

**Comment by qdstar** [comment]
公众号必须是服务号才能使用模板消息嘛？我是个订阅号，客服消息可以发送

**Comment by rememberber** [comment]
> 公众号必须是服务号才能使用模板消息嘛？我是个订阅号，客服消息可以发送

是的
