### ISSUE TITLE
小程序页面路径

### ISSUE THREAD

**Issue by poctopus** [rememberber/WePush#58]
最新版的程序v2.2在小程序页面路径设置为
pages/specialPage/specialPage?labelGroupId=26
只会进入小程序的首页，不知道是什么问题，麻烦拉大检测一下

**Comment by poctopus** [comment]
2.0的版本就没有这个问题。

**Comment by rememberber** [comment]
@poctopus 好的

**Comment by rememberber** [comment]
@poctopus 已修复，请更新
