### ISSUE TITLE
微信模板消息是否占用群发信息条数？

### ISSUE THREAD

**Issue by qq24021438** [rememberber/WePush#98]
微信模板消息是否占用群发信息条数？

**Comment by rememberber** [comment]
不占用

发送自 Windows 10 版邮件应用

发件人: qq24021438
发送时间: 2019年2月10日 19:05
收件人: rememberber/WePush
抄送: Subscribed
主题: [rememberber/WePush] 微信模板消息是否占用群发信息条数？ (#98)

微信模板消息是否占用群发信息条数？
